[package]
name = 'pallet-eth-sub-bridge'
authors = ['deeper.network dev']
description = 'pallet eth sub bridge.'
edition = '2018'
homepage = 'https://deeper.network'
license = 'Unlicense'
repository = 'https://github.com/deeper-chain/deeper-chain'
version = '2.0.0'


[package.metadata.docs.rs]
targets = ["x86_64-unknown-linux-gnu"]

[dependencies]
codec = { package = "parity-scale-codec", version = "1.3.4", default-features = false, features = ["derive"] }
frame-support = { version = "2.0.0", default-features = false}
frame-system = { version = "2.0.0", default-features = false}
sp-core = { version = "2.0.0", default-features = false}
sp-std = {version = "2.0.0", default-features = false}
sp-runtime = { version = "2.0.0", default-features = false}
sp-io = {version = "2.0.0", default-features = false}
serde = { version = "1.0.117", optional = true, features = ["derive"] }
timestamp = {version = "2.0.0", package="pallet-timestamp", default-features = false}
pallet-balances = { version = "2.0.0", default-features = false, path = "../balances" }
node-primitives = {version = '2.0.0', default-features = false, path = "../../primitives"}


[features]
default = ['std']
std = [
	'codec/std',
	'frame-support/std',
	'frame-system/std',
	'sp-core/std',
	'sp-std/std',
	'sp-runtime/std',
	'sp-io/std',
	'serde/std',
	'timestamp/std',
	'node-primitives/std',
	'pallet-balances/std',
]
